### ISSUE TITLE
Create a README for the project

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/obsidian-cypher-links#1]
Should create and maintain the README.md with general description of the project

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#3](https://github.com/nergal-perm/obsidian-cypher-links/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#3](https://github.com/nergal-perm/obsidian-cypher-links/issues/3), [#6](https://github.com/nergal-perm/obsidian-cypher-links/issues/6) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm all 2 puzzles are solved here: [#3](https://github.com/nergal-perm/obsidian-cypher-links/issues/3), [#6](https://github.com/nergal-perm/obsidian-cypher-links/issues/6).

**Comment by nergal-perm** [comment]
The simple README is created
