### ISSUE TITLE
Update links when the file is modified on disk

### ISSUE THREAD

**Issue by nergal-perm** [nergal-perm/obsidian-cypher-links#2]
The links for the current file should be updated when the file with the new frontmatter is saved.

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#4](https://github.com/nergal-perm/obsidian-cypher-links/issues/4), [#5](https://github.com/nergal-perm/obsidian-cypher-links/issues/5) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#5](https://github.com/nergal-perm/obsidian-cypher-links/issues/5) is still not solved; solved: [#4](https://github.com/nergal-perm/obsidian-cypher-links/issues/4).

**Comment by 0pdd** [comment]
@nergal-perm all 2 puzzles are solved here: [#4](https://github.com/nergal-perm/obsidian-cypher-links/issues/4), [#5](https://github.com/nergal-perm/obsidian-cypher-links/issues/5).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#7](https://github.com/nergal-perm/obsidian-cypher-links/issues/7) is still not solved; solved: [#4](https://github.com/nergal-perm/obsidian-cypher-links/issues/4), [#5](https://github.com/nergal-perm/obsidian-cypher-links/issues/5).

**Comment by 0pdd** [comment]
@nergal-perm all 3 puzzles are solved here: [#4](https://github.com/nergal-perm/obsidian-cypher-links/issues/4), [#5](https://github.com/nergal-perm/obsidian-cypher-links/issues/5), [#7](https://github.com/nergal-perm/obsidian-cypher-links/issues/7).

**Comment by nergal-perm** [comment]
fixed in #7
